version: '3'

services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

    networks:
      - net
    container_name: mysql
    volumes:
      - mysqldata:/var/lib/mysql 
  
  web:
    build: .
    container_name: form
    ports:
      - 5000:5000
    networks:
      - net
    depends_on:
      - mysql
  
networks:
  net:
    name: net
    driver: bridge

volumes:
  mysqldata: