version: '3'
services:
  form:
    build: .
    ports:
      - "5000:5000"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "100k"